print('Enter the first number to be added:')
first = input()
print('Enter the second number to be added:')
second = input()
print('Enter the third number to be added:')
third = input()
print('The sum is ' + first + second + third)
